(setq frame-resize-pixelwise t)
(setq highlight-nonselected-windows t)
(setq truncate-partial-width-windows nil)
(setq undo-limit 800000)
(setq undo-strong-limit undo-limit)
(setq-default fill-column 100)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
