(when (require 'which-key nil t)
  (setq which-key-lighter nil)
  (setq which-key-max-description-length 50)
  (setq which-key-sort-order 'which-key-local-then-key-order)
  (global-set-key (kbd "<f1> x") 'which-key-show-top-level)
  (which-key-mode))
